### ISSUE TITLE
YouTube Embed Disappearing

### ISSUE THREAD

**Issue by TheFlashDrive** [GoldenLys/WizardUI#3]
Whenever I play a YouTube video within an embed it doesn't appear, though the audio still plays. I've made sure no plugins like CollapseEmbeds or FavoriteMedia are interfering. 

https://github.com/GoldenLys/WizardUI/assets/39472296/134ae24b-2cfe-4cc1-afbf-4a14150ebf72

**Comment by GoldenLys** [comment]
Should be fixed with the latest update
